{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livekit-sip.fullname" . }}-config
  labels:
    {{- include "livekit-sip.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ tpl .Values.config.body . | indent 4 }}
{{- end }}
