apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "livekit-sip.fullname" . }}
  labels:
    {{- include "livekit-sip.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "livekit-sip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "livekit-sip.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: livekit-sip
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SIP_CONFIG_FILE
              value: {{ printf "%s/%s" .Values.config.mountPath .Values.config.fileName | quote }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: sip
              containerPort: {{ .Values.service.sipPort }}
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.config.mountPath | quote }}
              readOnly: true
              {{- with .Values.extraVolumeMounts }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "livekit-sip.fullname" . }}-config
            items:
              - key: {{ .Values.config.fileName }}
                path: {{ .Values.config.fileName | quote }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
