apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-sip.fullname" . }}
  labels:
    {{- include "livekit-sip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "livekit-sip.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.http }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
    - name: sip
      port: {{ .Values.service.sipPort }}
      targetPort: sip
      protocol: UDP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.sip }}
      nodePort: {{ .Values.service.nodePort.sip }}
      {{- end }}
