apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensips.fullname" . }}-config
  labels:
    {{- include "opensips.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ tpl .Values.config.body . | indent 4 }}
