apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensips.fullname" . }}
  labels:
    {{- include "opensips.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opensips.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opensips.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: opensips
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sip-udp
              containerPort: {{ .Values.service.sipPort }}
              protocol: UDP
            - name: sip-tcp
              containerPort: {{ .Values.service.sipPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ printf "%s/%s" .Values.config.mountPath .Values.config.fileName | quote }}
              subPath: {{ .Values.config.fileName | quote }}
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "opensips.fullname" . }}-config
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
