[rtpengine]
# Userspace forwarding (no kernel module)
table = -1

# Bind to all interfaces, advertise public IP in SDP
# Internal IP ! External/advertised IP
interface = 192.168.0.10

# Control socket for Kamailio (ng protocol)
listen-ng = 192.168.0.10:22222

# RTP port range (LiveKit-SIP uses 10000-19999, so we use 20000+)
port-min = 20000
port-max = 22221

# Timeouts
timeout = 60
silent-timeout = 3600

# Logging
log-level = 7
foreground = true
log-stderr = true
