[rtpengine]
# Staging value
# Userspace forwarding (set to -1 if the kernel module 'xt_RTPENGINE' is not loaded)
#table = 0

# FORMAT: <Private_IP>!<Public_IP>
# This tells rtpengine to bind to 10.12.0.49 but put 148.253.73.224 in the SDP
#interface = 10.12.0.49!148.253.73.224

# Control socket for Kamailio (must match your RTPENGINE_ADDR value)
#listen-ng = 10.12.0.49:22222

# RTP port range (LiveKit-SIP typically uses 10000-20000; ensure these are open in firewall)
#port-min = 20301
#port-max = 30000

# Dev
# Userspace forwarding (with kernel module)
table = -1

# Bind to all interfaces, advertise public IP in SDP
interface = 192.168.0.10

# Control socket for Kamailio
listen-ng = 192.168.0.10:22222

# RTP port range (LiveKit-SIP typically uses 10000-20000; ensure these are open in firewall)
port-min = 20301
port-max = 30000

# Timeouts & Logging (as per your initial file)
timeout = 60
silent-timeout = 3600
log-level = 6
foreground = false
log-stderr = false
tos = 184

# Performance & Jitter
jitter-buffer = 10
jb-clock-drift = true
num-threads = 4
no-xmlrpc = true

# understand the specific "-keep" flag sent by the controller.
sdp-attribute-preserve = rtcp-fb;confid;userid;floorctrl;floorid;maccaption

# Ensure rtpengine doesn't try to "clean up" the SDP by removing unknown codecs
codec-strip-all = false

# Be shure rtp/rtcp  demux
rtcp-mux = demux