# Generated by Django 5.2.8 on 2025-11-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_resource_users_alter_user_language'),
        ('core', '0015_application_and_more'),
    ]

    operations = [
    ]
