# Generated by Django 5.2 on 2025-12-04

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_merge_20251127_1653"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="E.164 formatted phone number assigned to this user",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format (e.g., +14155551234)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "trunk_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference to the SIP trunk providing this number",
                        max_length=255,
                        null=True,
                        verbose_name="SIP Trunk ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this phone number can receive calls",
                        verbose_name="Active",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_number",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
                "db_table": "meet_phone_number",
                "ordering": ("-created_at",),
            },
        ),
    ]
