name: Release Helm chart

on:
  push:
    branches:
      - main
    paths:
      - src/helm/meet/**

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: suitenumerique/ci/.github/workflows/_release-helm-chart.yml@main
